version: 0.2

phases:
  build:
    commands:
      - echo "Build started"
      - chmod +x scripts/*
      - grep "Congratulations" index.html

artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/**
  discard-paths: no
