version: 0.2

phases:
  build:
    commands:
      - echo "Build block"
      - ls -l
      - echo "Making scripts executable"
      - chmod +x scripts/*
      - echo "Running tests to check if 'Congratulations' present in index.html file"
      - grep "Congratulations" index.html

  post_build:
    commands:
      - echo "Post build phase"

artifacts:
  base-directory: CICD-working
  files:
    - index.html
    - appspec.yml
    - scripts/**
  discard-paths: no
